<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Akhil-PC" failures="0" tests="6" name="test.script.LoginTest" time="14.517" errors="1" timestamp="2024-12-03T09:46:03 IST" skipped="2">
  <testcase classname="test.script.LoginTest" name="verifyTheUserIsAbleToLoginUsingValidCredentials" time="2.090">
    <error message="Cannot invoke &quot;org.apache.poi.ss.usermodel.Cell.getStringCellValue()&quot; because &quot;c&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Cell.getStringCellValue()" because "c" is null
at utilities.ExcelUtilities.getStringData(ExcelUtilities.java:24)
at test.script.LoginTest.verifyTheUserIsAbleToLoginUsingValidCredentials(LoginTest.java:17)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- verifyTheUserIsAbleToLoginUsingValidCredentials -->
  <testcase classname="test.script.LoginTest" name="verifyTheUserIsAbleToLoginUsingValidCredentials" time="2.134">
    <skipped/>
  </testcase> <!-- verifyTheUserIsAbleToLoginUsingValidCredentials -->
  <testcase classname="test.script.LoginTest" name="verifyTheUserIsAbleToLoginUsingValidCredentials" time="2.489">
    <skipped/>
  </testcase> <!-- verifyTheUserIsAbleToLoginUsingValidCredentials -->
  <testcase classname="test.script.LoginTest" name="verifyTheUserIsAbleToLoginUsingValidUsernameAndIncorrectPassword" time="2.614"/>
  <testcase classname="test.script.LoginTest" name="verifyTheUserIsAbleToLoginUsingIncorrectUsernameAndValidPassword" time="2.565"/>
  <testcase classname="test.script.LoginTest" name="verifyTheUserIsAbleToLoginUsingIncorrectCredentials" time="2.625"/>
</testsuite> <!-- test.script.LoginTest -->
